CREATE TYPE "CanonicalEntityType" AS ENUM ('PERSON', 'HOUSEHOLD', 'ADDRESS', 'VEHICLE', 'BUSINESS', 'POLICY', 'ACCOUNT');
CREATE TYPE "FactRevisionStatus" AS ENUM ('ACTIVE', 'CORRECTED', 'RETRACTED');
CREATE TYPE "ProviderCaseStatus" AS ENUM ('SUBMITTED', 'ACKNOWLEDGED', 'UNDER_REVIEW', 'ACTION_REQUIRED', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', 'APPEALED');
CREATE TYPE "CitizenTaskStatus" AS ENUM ('OPEN', 'WAITING', 'COMPLETED', 'DISMISSED');

CREATE TABLE "CanonicalEntity" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "type" "CanonicalEntityType" NOT NULL, "displayName" TEXT NOT NULL, "externalKey" TEXT, "dataJson" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CanonicalEntity_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EntityRelationship" ("id" TEXT NOT NULL, "fromId" TEXT NOT NULL, "toId" TEXT NOT NULL, "kind" TEXT NOT NULL, "validFrom" TIMESTAMP(3), "validTo" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "EntityRelationship_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JourneyEntityLink" ("id" TEXT NOT NULL, "journeyId" TEXT NOT NULL, "entityId" TEXT NOT NULL, "role" TEXT NOT NULL, CONSTRAINT "JourneyEntityLink_pkey" PRIMARY KEY ("id"));
CREATE TABLE "JourneyTemplateVersion" ("id" TEXT NOT NULL, "templateKey" TEXT NOT NULL, "version" INTEGER NOT NULL, "lifeEvent" TEXT NOT NULL, "configJson" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "JourneyTemplateVersion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FactRevision" ("id" TEXT NOT NULL, "factId" TEXT NOT NULL, "valueJson" JSONB NOT NULL, "sourceType" "SourceType" NOT NULL, "sourceRef" TEXT, "confidence" DOUBLE PRECISION, "status" "FactRevisionStatus" NOT NULL DEFAULT 'ACTIVE', "supersedesId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FactRevision_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProviderCase" ("id" TEXT NOT NULL, "journeyId" TEXT NOT NULL, "nodeKey" TEXT NOT NULL, "provider" TEXT NOT NULL, "status" "ProviderCaseStatus" NOT NULL, "scenario" TEXT NOT NULL, "reasonCode" TEXT, "nextTransitionAt" TIMESTAMP(3), "payloadJson" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProviderCase_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CitizenTask" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "journeyId" TEXT, "kind" TEXT NOT NULL, "title" TEXT NOT NULL, "detail" TEXT NOT NULL, "status" "CitizenTaskStatus" NOT NULL DEFAULT 'OPEN', "dueAt" TIMESTAMP(3), "reminderAt" TIMESTAMP(3), "metadataJson" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CitizenTask_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ConsentGrant" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "purpose" TEXT NOT NULL, "scopeJson" JSONB NOT NULL, "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), CONSTRAINT "ConsentGrant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AccessEvent" ("id" TEXT NOT NULL, "profileId" TEXT NOT NULL, "actor" TEXT NOT NULL, "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT NOT NULL, "metadataJson" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AccessEvent_pkey" PRIMARY KEY ("id"));
ALTER TABLE "OutputDocument" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "supersedesId" TEXT, ADD COLUMN "checksum" TEXT;
INSERT INTO "JourneyTemplateVersion" ("id", "templateKey", "version", "lifeEvent", "configJson") SELECT CONCAT("id", '-v', "version"), "id", "version", "lifeEvent", "configJson" FROM "JourneyTemplate";
CREATE INDEX "CanonicalEntity_profileId_type_idx" ON "CanonicalEntity"("profileId", "type");
CREATE UNIQUE INDEX "CanonicalEntity_profileId_type_externalKey_key" ON "CanonicalEntity"("profileId", "type", "externalKey");
CREATE UNIQUE INDEX "JourneyEntityLink_journeyId_entityId_role_key" ON "JourneyEntityLink"("journeyId", "entityId", "role");
CREATE UNIQUE INDEX "JourneyTemplateVersion_templateKey_version_key" ON "JourneyTemplateVersion"("templateKey", "version");
CREATE INDEX "FactRevision_factId_createdAt_idx" ON "FactRevision"("factId", "createdAt");
CREATE UNIQUE INDEX "ProviderCase_journeyId_nodeKey_key" ON "ProviderCase"("journeyId", "nodeKey");
CREATE INDEX "CitizenTask_profileId_status_dueAt_idx" ON "CitizenTask"("profileId", "status", "dueAt");
CREATE INDEX "AccessEvent_profileId_createdAt_idx" ON "AccessEvent"("profileId", "createdAt");
ALTER TABLE "CanonicalEntity" ADD CONSTRAINT "CanonicalEntity_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EntityRelationship" ADD CONSTRAINT "EntityRelationship_fromId_fkey" FOREIGN KEY ("fromId") REFERENCES "CanonicalEntity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EntityRelationship" ADD CONSTRAINT "EntityRelationship_toId_fkey" FOREIGN KEY ("toId") REFERENCES "CanonicalEntity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JourneyEntityLink" ADD CONSTRAINT "JourneyEntityLink_journeyId_fkey" FOREIGN KEY ("journeyId") REFERENCES "JourneyInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JourneyEntityLink" ADD CONSTRAINT "JourneyEntityLink_entityId_fkey" FOREIGN KEY ("entityId") REFERENCES "CanonicalEntity"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "JourneyInstance" ADD CONSTRAINT "JourneyInstance_templateId_templateVersion_fkey" FOREIGN KEY ("templateId", "templateVersion") REFERENCES "JourneyTemplateVersion"("templateKey", "version") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FactRevision" ADD CONSTRAINT "FactRevision_factId_fkey" FOREIGN KEY ("factId") REFERENCES "Fact"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProviderCase" ADD CONSTRAINT "ProviderCase_journeyId_fkey" FOREIGN KEY ("journeyId") REFERENCES "JourneyInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CitizenTask" ADD CONSTRAINT "CitizenTask_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CitizenTask" ADD CONSTRAINT "CitizenTask_journeyId_fkey" FOREIGN KEY ("journeyId") REFERENCES "JourneyInstance"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConsentGrant" ADD CONSTRAINT "ConsentGrant_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AccessEvent" ADD CONSTRAINT "AccessEvent_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
